### ISSUE TITLE
Giving a group access to part of a page

### ISSUE THREAD

**Issue by jerauf** [rydurham/Sentinel#121]
I know that I can use this to give access to part of a page by permission level:

Sentry::getUser()->hasAccess('admin')

But what if I have a group called 'editor' that has permission "users" but I need to restrict part of a page so that only the 'editor' group can see it?

**Comment by rydurham** [comment]
There is another helper function from Sentry that will let you see if a user is a member of a particular group:

```php
$editorGroup = Sentry::findGroupByName('Editor');

if (Sentry::getUser()->inGroup($editorGroup)) 
{
    ...
}
```

Note that you must use the exact proper name of the group in the ```findGroupByName``` function - "editor" and "Editor" will be seen as different.

**Comment by jerauf** [comment]
That worked. Thank you!
