### ISSUE TITLE
Wrong arguments in unique validation for groups.

### ISSUE THREAD

**Issue by fireball70** [rydurham/Sentinel#122]
Found that can't edit and create groups.
Something going wrong with unique validation (wrong arguments in method).
vendor/rydurham/sentinel/src/Sentinel/Service/Form/Group/GroupForm.php:
```
	protected function valid(array $input)
	{ 
		return $this->validator->with($input)->updateUnique('name', $input['id'], 'id')->passes();		
	}
```

Maybe something like this:
```
    protected function valid(array $input)
    {
        // if "create" set input id to 0 to pass the validation...
        $input['id'] = isset($input['id']) ? $input['id'] : 0;
        // wrong arguments in "updateUnique" method.
        return $this->validator->with($input)->updateUnique('name','name', $input['id'])->passes();
    }
```

**Comment by fireball70** [comment]
Hm... "Edit" working fine after your update. But try to "create" new group - input['id'] is not set and return:
ErrorException (E_UNKNOWN)
Undefined index: id

**Comment by rydurham** [comment]
This should now be fixed - thanks for the heads up!
