### ISSUE TITLE
Redirect Logged in user on Login Page

### ISSUE THREAD

**Issue by kJamesy** [rydurham/Sentinel#123]
I am looking for a way to prevent the logged in user from seeing the login page, without editing the package. That's to say that if the user calls the login route and they are already logged in, redirect them to the default post-login page.

Any ideas?

**Comment by rydurham** [comment]
You could try disabling the default sentinel login routing (via the config) and then building out a new login route with a custom filter to handle the redirect.  

This is probably something the package should do anyway.

**Comment by rydurham** [comment]
This has now been implemented in Sentinel 2.0.

**Comment by kJamesy** [comment]
Thanks for that.
Could you possibly do the same for the dev-master branch?

**Comment by kJamesy** [comment]
Ok, I have dug my way round it and stumbled across some bugs in 2.0 for which I'll open a new issue.

**Comment by rydurham** [comment]
Yes - that should be doable.    

There is no documentation for 2.0 yet - that is on my list.

**Comment by rydurham** [comment]
I have now implemented this in the master branch.

**Comment by kJamesy** [comment]
Cheers
