### ISSUE TITLE
Bugs in Filters; Sentinel 2.0

### ISSUE THREAD

**Issue by kJamesy** [rydurham/Sentinel#126]
I upgraded to the dev-develop branch but it seems the filters.php is trying to redirect to views that don't exist. Because it is fetching the paths from the config that doesn't exist, the application silently breaks (without any errors).
This file: https://github.com/rydurham/Sentinel/blob/develop/src/filters.php#L41 makes use of Config items that don't exist.
While on the same issue, could the login and logout routes be added to the routing.php config and also the post_login and post_logout configs as per https://github.com/rydurham/Sentinel/blob/master/src/config/config.php#L71 reinstated in version 2.0?

Many thanks.

**Comment by rydurham** [comment]
Good catch!  I will have a look at it. 

The post_login and post_logout configuration options are still there, but they have been renamed to 'session.create' and 'session.destroy'.

**Comment by rydurham** [comment]
This is now fixed. Thank you!

**Comment by kJamesy** [comment]
Cheers Ryan
