### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by donenvy** [rydurham/Sentinel#127]
Hi all,

I am sure I must be installing this wrong. But I followed the instructions, after doing all the steps mentioned on git page using composer. I had to manually download the class files, config files and the sentinal folder files as they were missing. 

Afterwards I set a homepage and had to manually go over to /register. When I log in, it redirects me to an empty homepage. I have to revisit /register to access the profile. 

On registration, it redirects me to homepage with no success message, on validating email it redirects me to homepage with no messages. 

I am guessing that I have installed this incorrectly? Can somebody advise?

On a fresh laravel install, I used 
composer require rydurham/sentinel

and so forth as instructed.

**Comment by rydurham** [comment]
What version of Sentinel does your composer.json file specify?

**Comment by donenvy** [comment]
I have in there 

"rydurham/sentinel": "~1.4"

**Comment by rydurham** [comment]
Ok - that is good.  My guess is that this is a composer problem - for whatever reason it didn't pull down the entire package.  Try deleting the rydurham folder from your vendor directory, and running "composer update --prefer-source".

**Comment by donenvy** [comment]
This is what I got

# composer update --prefer-source
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing rydurham/sentinel (v1.4.24)
    Cloning d46ba728c127a8b6d876cd2177ce0d3072018166
    Failed to download rydurham/sentinel from source: Failed to clone git@github
.com:rydurham/Sentinel.git, git was not found, check that it is installed and in
 your PATH env.

'git' is not recognized as an internal or external command,
operable program or batch file.

    Now trying to download from dist
  - Installing rydurham/sentinel (v1.4.24)
    Loading from cache

**Comment by rydurham** [comment]
Do you have git installed locally?  What is your host OS?  Have you had issues with any other packages?

**Comment by donenvy** [comment]
Im using xampp, I have been able to install everything else so far. I am not sure if I have git installed, how do I check?

**Comment by rydurham** [comment]
Open your terminal program and run ```git --version``` - what is the output?

**Comment by donenvy** [comment]
git is not recognised as an internal or external command

**Comment by rydurham** [comment]
And you say you have used Composer to pull in other pacakges with no trouble?

**Comment by donenvy** [comment]
Just tried it with another package confide, it's installed it all ok with no errors

**Comment by rydurham** [comment]
I am not sure what to say.   The error message you got would indicate that Composer needs git and can't find it.

**Comment by donenvy** [comment]
how would one install it manually?

**Comment by rydurham** [comment]
http://git-scm.com/downloads

If you are on a mac I am told it is better to use Homebrew, but I don't have any experience with that.

**Comment by rydurham** [comment]
Were you able to sort this out?

**Comment by rydurham** [comment]
I am going to close this for now.
