### ISSUE TITLE
Composer update from earlier version breaks user registration

### ISSUE THREAD

**Issue by edsuna** [rydurham/Sentinel#128]
I started using Sentinel in March of 2014. I installed my application on a production machine and it has been running since. I recently needed to update the project and ran composer update to pull in some new packages. This also updated Sentinel. Now user registration is failing because the username column is missing from the users table. Looking at the code history it seems that instead of creating a new migration file to add the username column the initial migration file was just modified. This means that on my production environment when I try to run migrations it tells me that that there are no migrations to run. So I don't have a way of properly migrating the users table to add the username column.

**Comment by rydurham** [comment]
It is true that the addition of the username field was not handled in an ideal way.   In the short term you have two options:  You can turn off the use of the username in the config file, or you can create a new migration to handle the addtion of the username field for your DB.

**Comment by edsuna** [comment]
How can I turn it off in the config file?

**Comment by rydurham** [comment]
Take a look at the config file in the repo - it is likely that the config file you published when you first set up the site is missing this option.  At the very bottom you will see  ```'allow_usernames' => true```. Set this to false and you should be good to go.

**Comment by edsuna** [comment]
Will this be fixed in a future release or is this something that I need to add to my repository?

**Comment by rydurham** [comment]
If you want a separate migration file you should add it to your repo.

**Comment by edsuna** [comment]
No I meant the config file option. That is not part of my repository currently as it is pulled in by composer. If I turn off that option as a long term solution I would need to add that to my repository since pulling it in via composer would overwrite the change.

**Comment by rydurham** [comment]
If you haven't already, your best bet is to publish the config file: 

```bash
php artisan config:publish rydurham/sentinel
```

This will put a copy of the package config file in your application config folder, and you can adjust it as necessary. 

If it has already been published you can re-publish it but your current settings will be overwritten.

**Comment by rydurham** [comment]
I have now moved the username column into a separate migration file - this should resolve this problem going forward.

**Comment by edsuna** [comment]
I did a composer update but got Nothing to install of update.

I am using 1.* in my composer.json
"rydurham/sentinel": "1.*",

**Comment by rydurham** [comment]
I haven't tagged a new version of the master branch yet - I will do that later today.

**Comment by rydurham** [comment]
I hav just tagged v1.425 which includes the new migration file.

**Comment by edsuna** [comment]
Thank you that fixed the problem.
