### ISSUE TITLE
'Can't Use Function Return Value in Write Context' Error

### ISSUE THREAD

**Issue by kJamesy** [rydurham/Sentinel#131]
This error is thrown when using PHP 5.4.12 although the minimum version of PHP for the package is 5.4.
No error with PHP 5.5
Please see 
http://stackoverflow.com/questions/1532693/weird-php-error-cant-use-function-return-value-in-write-context 
Screenshot attached
![sentinelerror](https://cloud.githubusercontent.com/assets/4100964/6061155/28d5f482-ad3d-11e4-95f8-dc18fee67775.jpg).

**Comment by rydurham** [comment]
Which version of the package are you using here?

**Comment by kJamesy** [comment]
That would be the dev

**Comment by rydurham** [comment]
Ah - yes.  This will be resolved in the next alpha release when we switch to L5 form requests. Which I guess means I should bump up the minimum php version to 5.4.

**Comment by rydurham** [comment]
This should now be resolved by happenstance.
