### ISSUE TITLE
[5.0] composer fails

### ISSUE THREAD

**Issue by ThePoet444** [rydurham/Sentinel#132]
couldn't get it to work. I think the mitch/hashids is failing for whatever reason. I tried a bunch of different ways to try and get it loaded into my app. None of it worked. I know it's still alpha and things will change, but figured I would let you know.

**Comment by rydurham** [comment]
Thanks for the heads up!  I will take a look.

**Comment by rydurham** [comment]
I have just tagged a new alpha version that should fix this.

**Comment by ThePoet444** [comment]
Finally installs but your service proder fails now:

```
exception 'ReflectionException' with message 'Class Mitch\Hashids\HashidsServiceProvider does not exist' in /home/vagrant/Code/RS/vendor/rydurham/sentinel/src/Sentinel/Commands/SentinelPublishCommand.php:196
```

**Comment by rydurham** [comment]
This should be fixed in the master develop branch - try pulling in
dev-develop and see if that helps.

**Comment by ThePoet444** [comment]
I should open a new issue, but eh.. if you want hashids, someone referenced this:  https://github.com/vinkla/hashids

**Comment by rydurham** [comment]
That looks perfect!  Thank you.

**Comment by rydurham** [comment]
This is now implemented in the newest alpha version (a5).

**Comment by ThePoet444** [comment]
Look great! Thanks! :)
