### ISSUE TITLE
Don't supports personal app namespace

### ISSUE THREAD

**Issue by alograg** [rydurham/Sentinel#137]
A lot of thing use default app name and throw exceptions when change the default name space.

**Comment by rydurham** [comment]
This should be fixed in dev-master - once I know it is working properly I will tag a new release.

**Comment by alograg** [comment]
I fixed change all:
use App\Http\Requests\Request; -> use Illuminate\Foundation\Http\FormRequest;
extends Request -> extends FormRequest

**Comment by rydurham** [comment]
This is fixed in v2.1.0.  You may need to re-publish the view files.

**Comment by alograg** [comment]
thanks
