### ISSUE TITLE
error on app/profile/edit when select theme on sentinel:publish

### ISSUE THREAD

**Issue by llstarscreamll** [rydurham/Sentinel#138]
Hi!!
here is the issue list:

--theme="materialize"  =>  ErrorException
--theme="gumby"  =>  blank page
--theme="materialize"  =>  ok
--theme="boostrap"  =>  ok
--theme="foundation"  =>  blank page

more errors with some themes on other routes such as:
- app/users/qjr9j2/edit
- app/groups/qjr9j2/edit
- app/users/create

and a user can suspend himself?

clean install, nothing edited or touched...

or maybe I'm doing something wrong?

Thanks!! Great job!!   ^_^

**Comment by rydurham** [comment]
Interesting - I will look in to this and see if I can figure out what is going on.

**Comment by rydurham** [comment]
I have pushed fixes to some of these issues - if you can find additional specific pages in specific themes that have problems let me know!  Thank you!

**Comment by llstarscreamll** [comment]
Hello !! I found other:

theme = "bootstrap"
1. app.local/users-> blank page -> after post create user form
2. app.local/profile/edit -> bad format on notification when trying to change password with less than 6 characters
3. app.local/profile -> errorException line 12 -> it happens after ban or suspend any user

theme = "foundation"
1. app.local/profile -> errorException line 13 -> it happens after ban or suspend any user
2. app.local/profile/edit -> errorException line 12
3. app.local/users/create -> blank page
4. app.local/users -> delete button does not work, can't delete any user
5. close notification button does not work
6. app.local/groups/y3yrw0/edit -> blank page
7. app.local/groups -> delete group button does not work
8. app.local/groups/create -> bad format on notification when typing wrong data
9. app.local/sessions/create -> bad format on notification when typing wrong data
10. app.local/register -> you fill the same data several times and it does not notify error or warning, only redirects to login without notifications...

I have not set mail settings...
I will review later a little more ... ^_^

**Comment by rydurham** [comment]
I wasn't able to reproduce all of these, but I have fixe the ones I was able to catch.  Feel free to submit a PR with improved layout formatting.

Thank you!
