### ISSUE TITLE
Error: Undefined offset: 0 at $this->hashids->decode($hash)[0];

### ISSUE THREAD

**Issue by ideadx** [rydurham/Sentinel#142]
File: /vendor/rydurham/sentinel/src/controllers/UserController.php
route: users/{$id}
function: 

 public function show($hash)
    {
        // Decode the hashid
        $id = $this->hashids->decode($hash)[0];

        // Get the user
        $user = $this->userRepository->retrieveById($id);

        return $this->viewFinder('Sentinel::users.show', ['user' => $user]);
    }

**Comment by ideadx** [comment]
This issue fixed in alpha v6: https://github.com/rydurham/Sentinel/issues/134
Any updates as to when will it be available?

**Comment by rydurham** [comment]
The change made in Alpha v6 was incorporated into the current 2.* branch - what version are you using?

**Comment by ideadx** [comment]
I am using v2.1 and still the same issue.

**Comment by rydurham** [comment]
I am not able to replicate this. Is the value being passed to the url a valid hash?

**Comment by ideadx** [comment]
Not using hash.
Current url to display user : app.com/user/show/3
Do I pass Hash in url?

**Comment by rydurham** [comment]
Ah - that is the problem.   Sentinel is expecting to receive a hash from the URL.   Here is one way to create that link: 

```php
<a href="{{ action('\\Sentinel\Controllers\UserController@show', array($user->hash)) }}">{{ $user->email }}</a>
```

**Comment by ideadx** [comment]
Works like Charm :+1:  Thanks rydurham
