### ISSUE TITLE
Can't download the Repo

### ISSUE THREAD

**Issue by Lahori-Jawan** [rydurham/Sentinel#144]
I am trying to download the sentinel 2 for laravel 5 on windows with composer but every time i try, it fails. I did just the same as is stated but don't know why it is failing. Please help!

**Comment by rydurham** [comment]
There are two different things you can try, if you haven't already.   First, you can run ```composer update --prefer-source``` to make sure you are not installing from cache.  Secondly, you can try running ```composer update -v``` or ```composer update -vvv``` to get more details about what is going on behind the scenes.

**Comment by Lahori-Jawan** [comment]
after i passed first command i.e. prefer-source, following is the result 
![error](https://cloud.githubusercontent.com/assets/7579344/7380129/9e864ed2-edae-11e4-80d2-c9a554d21848.PNG)

**Comment by Lahori-Jawan** [comment]
this is the error after passing 2nd command to composer as you suggested i.e. update -vvv ![error2](https://cloud.githubusercontent.com/assets/7579344/7380361/3e3dea74-edb0-11e4-80b8-541ece4128c3.PNG)

**Comment by rydurham** [comment]
I am not sure what the problem is.  Is there anything else in your composer.json file other than this package?

**Comment by rydurham** [comment]
Were you able to solve this problem?

**Comment by Lahori-Jawan** [comment]
Sorry for late response as I was a bit out of touch. Your prediction was right. I had another package i.e. "cartalyst/sentinel": "2.0.*", listed in my composer.json file. After removing that package from require array and using your package i.e. "rydurham/sentinel": "~2.1" with composer update --prefer-source command, I just downloaded it successfully. Thank you so much for your help!

**Comment by rydurham** [comment]
Excellent - I am glad you were able to sort it out.
