### ISSUE TITLE
Preventing access to default route using sentry.auth?

### ISSUE THREAD

**Issue by bfarrgaynor** [rydurham/Sentinel#145]
I think I'm a little lost... (Using Laravel 5)

I modified my 'home' route with the following:
```
Route::get('/', array('middleware' => 'sentry.auth', 'as' => 'home', function()
{
    return View::make('home');
}));
```
But I can still access this route even while *not* logged in. The header changes, but shouldn't I be redirected to the login page?

I tried changing it to:
```
Route::get('/', array('middleware' => 'auth', 'as' => 'home', function()
{
    return View::make('home');
}));
```
... and it kind of works as expected, but then after logging in I get an error when I'm brought back to the home route. Forcefully logging out by going to /auth/logout works.

https://www.dropbox.com/s/k6al44ou24loc3i/Screenshot%202015-04-30%2023.39.40.png?dl=0

I feel like I must be doing something wrong with the route setup?

Ideally I would like my project to have a login wall, so if you don't have a session you are taken directly to the login screen, then after you login you are taken to the home page.

**Comment by rydurham** [comment]
Interesting.  I tried using this route:

```php
Route::get('/', array('middleware' => 'sentry.auth', 'as' => 'home', function()
{
    return view('welcome');
}));
```

in a new L5/Sentinel installation and it is working as expected.   I am not sure what could be causing this problem for you.

A couple questions, just to get a better sense of your setup: 

- Is this a brand new L5 application or are you porting from L4? 
- Did you register the Sentinel middleware in the ```kernel.php``` file?  What other middleware is registered there? 
-  Have you modified any of the default sentinel config values?
- Could there be another route named "home" in your routes file?
- Did you run the ```php artisan fresh``` command when you were first setting up the application?  This is not a requirement, but I am curious.

**Comment by bfarrgaynor** [comment]
> Is this a brand new L5 application or are you porting from L4?
Brand new.

> Did you register the Sentinel middleware in the kernel.php file? What other middleware is registered 
> there?

Yes I did. 
```php
class Kernel extends HttpKernel {

	/**
	 * The application's global HTTP middleware stack.
	 *
	 * @var array
	 */
	protected $middleware = [
		'Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode',
		'Illuminate\Cookie\Middleware\EncryptCookies',
		'Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse',
		'Illuminate\Session\Middleware\StartSession',
		'Illuminate\View\Middleware\ShareErrorsFromSession',
		'Oasis\Http\Middleware\VerifyCsrfToken',

	];

	/**
	 * The application's route middleware.
	 *
	 * @var array
	 */
	protected $routeMiddleware = [
		'auth' => 'Oasis\Http\Middleware\Authenticate',
		'auth.basic' => 'Illuminate\Auth\Middleware\AuthenticateWithBasicAuth',
		'guest' => 'Oasis\Http\Middleware\RedirectIfAuthenticated',
        'sentry.auth' => 'Sentinel\Middleware\SentryAuth',
        'sentry.admin' => 'Sentinel\Middleware\SentryAdminAccess',
	];

}

```

> Have you modified any of the default sentinel config values?
No

> Could there be another route named "home" in your routes file?

There *was* but I commented it out.

```php

//Route::get('/', 'WelcomeController@index');
//Route::get('home', 'HomeController@index');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);


Route::get('/', array('middleware' => 'sentry.auth', 'as' => 'home', function()
{
    return View::make('home');
}));

```

> Did you run the php artisan fresh command when you were first setting up the application? 
> This is not a requirement, but I am curious.

No I didn't. Should I?

**Comment by bfarrgaynor** [comment]
Wait.... 

I think I figured it out. I was getting confused between the Laravel auth stuff and Sentinel by keeping the old .

```php
Route::controllers([
    'auth' => 'Auth\AuthController',
    'password' => 'Auth\PasswordController',
]);

```

... in my route.php file I was getting thrown to the native login instead of yours.

**Comment by rydurham** [comment]
That is great news.  I will add a note about those default controllers to the readme.

**Comment by bfarrgaynor** [comment]
Are you taking pull requests? I might be able to contribute a more verbose set of instructions to expand on some things I struggled with. eg. Clearing the default user migrations needs more explanation and the user table is missing the remember_token field. I'd be happy to help out.

**Comment by rydurham** [comment]
Yes - absolutely.  Thank you.

One of my original goals was to set up this package so that it could work
as a direct replacement of the default Auth system - however it is not
quite at a point where that will work seamlessly.  Sentry uses a field
called "persist_code" instead of "remember_token" - if/when I am able to
finish implementing all of the default Auth interfaces, that should become
a non-issue.
ᐧ
