### ISSUE TITLE
Undefined property: Sentinel\Repo\Session\SentrySession::$sentryUserProvider

### ISSUE THREAD

**Issue by alegalviz** [rydurham/Sentinel#146]
In line 153 of 
https://github.com/rydurham/Sentinel/blob/1.4/src/Sentinel/Repo/Session/SentrySession.php#L153

It happen in a login with a correct user name but wrong password.

Thank you for Sentinel!

Alek

**Comment by rydurham** [comment]
This should now be fixed in v1.4.27.
