### ISSUE TITLE
change the email templates

### ISSUE THREAD

**Issue by AlaaAttya** [rydurham/Sentinel#147]
Hello buddy,

just wanted to ask how can i extend the email templates for configure new ones. If you did not manage it do you intend to, i may be interested to start working on it and send you a pull request

Thanks,

**Comment by rydurham** [comment]
Hello!  It is possible to customize the existing email templates.  If you have not done so already, make sure to publish the package views and config files.  Once that is done, the content of the emails will be in in your views directory, and you can edit them as you would any other view.   To customize the subject lines of the emails, you will need to edit the relevant section of the config file(s).  

Does that answer the question?

**Comment by AlaaAttya** [comment]
@rydurham yup it's the answer, thanks man :+1:
