### ISSUE TITLE
Escaped HTML Output in Laravel 5

### ISSUE THREAD

**Issue by almoe-mm** [rydurham/Sentinel#148]
Hi Ryan,
thank you for your wrapper, we just started using it and noticed that there is lot like this:
{{ Form::label('edit_memberships', 'Permissions') }}
which ends up as escaped HTML code since Laravel 5 now uses
{!! Form::label('edit_memberships', 'Permissions') !!}
for raw output.

Are you already aware of this?

Cheers,
Matt

**Comment by almoe-mm** [comment]
Ah actually it looks like it's just the groups/edit.blade.php - fast fix :)

**Comment by rydurham** [comment]
Thanks for catching that - is it a problem in the other themes as well?   Feel free to submit a pull request, if you would like.

**Comment by almoe-mm** [comment]
Hi Ryan,
it looks like it’s just in these files:

vendor/rydurham/sentinel/src/views/foundation/groups/edit.blade.php
vendor/rydurham/sentinel/src/views/foundation/users/resend.blade.php
vendor/rydurham/sentinel/src/views/foundation/groups/edit.blade.php

Searching for "{{ Form::"

Cheers,
Matt

**Comment by rydurham** [comment]
Good catch.  I will update that in the next release.
