### ISSUE TITLE
A hasher has not been provided for the user.

### ISSUE THREAD

**Issue by oidnus** [rydurham/Sentinel#149]
```
$user = \Sentinel\Models\User::find(2);
$user->password = 'admin';
$user->save();
```
and have  error 
RuntimeException
A hasher has not been provided for the user.

**Comment by lawrence615** [comment]
Getting the same exception when trying to create a new user by injecting User and Group repos in my controller.

**Comment by rydurham** [comment]
Are you extending the Sentinel user model?

**Comment by lawrence615** [comment]
Not really.  I am injecting user repository in my controller then calling
the store function for creating a user

**Comment by rydurham** [comment]
The solution is to take advantage of the Eloquent boot method in your User model to instantiate the hasher object.  This is now done automatically by the Sentinel User Model, so you can ether extend that model or you can add this to your user model: 

```php
/**
 * Set the Sentry User Model Hasher to be the same as the configured Sentry Hasher
 */
public static function boot()
{
    parent::boot();
    static::setHasher(app()->make('sentry.hasher'));
}
```
