### ISSUE TITLE
Ability to redefine validators

### ISSUE THREAD

**Issue by tusharvikky** [rydurham/Sentinel#150]
Hey,

Is there any way by which i can remove password confirmation validator. I know it not the right way to do. But thats what the project needs now. And if we can add configs for it would be great.

**Comment by rydurham** [comment]
There is not currently a built in way to do this.  However, if you create your own controller to handle the password related routes you can then use a custom form request to validate the data any way you wish.

**Comment by tusharvikky** [comment]
Ain't there any way to just override certain controller function? and not override the complete routes of the package? Like just the 'RegistrationController@register'? If it doesn't it will lead to just plain copy paste of other function and controllers.

**Comment by rydurham** [comment]
My advice would be to turn off the package routes via the config file and then copy the Sentinel routes file into your master routes file, where you can then make whatever edits you want.

**Comment by tusharvikky** [comment]
Thanks. Copied all routes and controllers and edited them according to my need.

**Comment by tusharvikky** [comment]
I migrated as mentioned. But during registration, I get
![image](https://cloud.githubusercontent.com/assets/1810991/7996019/d8d4e5dc-0b39-11e5-87e8-a49afab4eea0.png)

**Comment by rydurham** [comment]
The problem is probably one of these two things: 

- Does your user model extend the Sentinel\Models\User class? 
- Have you published the Sentry config file and does the User model setting in that file point to your application's user model?

**Comment by tusharvikky** [comment]
Yes, User Model extends Sentinel\Models\User class. And the pulished sentry config User model is pointed to Sentinel\Models\User. But still same error.

**Comment by rydurham** [comment]
Try changing the Sentry config file to point to your custom user class.

**Comment by tusharvikky** [comment]
Tried that, didnt work. Same error.

**Comment by tusharvikky** [comment]
Sorry my mistake. I didn't something stupid. Thanks for the help.
