### ISSUE TITLE
Add Support for Laravel 5.1

### ISSUE THREAD

**Issue by carbontwelve** [rydurham/Sentinel#151]
rydurham/sentinel v2.1.7 requires illuminate/contracts 5.0 and therefore will not install with laravel 5.1.

**Comment by rydurham** [comment]
This is in progress.

**Comment by carbontwelve** [comment]
Good to hear :+1: I was going to look into adding this, this morning as a project I am working on requires sentinel, but another project needed to go live. 

Do you have an eta for when this may be available?

**Comment by rydurham** [comment]
I am hoping I will have it ready in the next day or so; there are some
other tweaks I want to implement in addtion to adding support for 5.1.

**Comment by ideadx** [comment]
Any way we can add param to middleware 
e.g:
$this->middleware('sentry.admin',['only'->'index'])

**Comment by carbontwelve** [comment]
This has now been done so I am closing this issue :)
