### ISSUE TITLE
sentinel:publish on Laravel 5.1 issue

### ISSUE THREAD

**Issue by leo4all** [rydurham/Sentinel#156]
[InvalidArgumentException]          
The "force" option does not exist

**Comment by rydurham** [comment]
There is no force option for the publish command - it should not be necessary.

**Comment by head82** [comment]
i had the same problem and could solve that by adding an .env file with the following content:

    APP_ENV=local

see http://laravel.com/docs/5.1#environment-configuration for more informations.

see file vendor/rydurham/sentinel/src/Sentinel/Commands/SentinelPublishCommand.php for following implementation:

        class SentinelPublishCommand
        {
                ...
                public function fire()
                {
                // Don't allow this command to run in a production environment
                if (!$this->confirmToProceed()) {
                    return;
                }
                ...
