### ISSUE TITLE
Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by lostfocus** [rydurham/Sentinel#158]
I just tried to make a clean new install of Laravel 5.1.1 with the 2.2 branch of Sentinel and when I try to run `php artisan migrate` it breaks when adding a unique key to the email field:

    [Illuminate\Database\QueryException]                                                                                                              
    SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `users` add unique users_email_unique(`email`)) 

I am pretty sure that this is because I switched the database form `utf8` to `utf8mb4` - I don't really have an idea how to still get the unique key on that field with that charset.

**Comment by lostfocus** [comment]
I got around the problem by adding

    $table->charset = 'utf8';
    $table->collation = 'utf8_unicode_ci';

to `MigrationCartalystSentryInstallUsers` and `MigrationCartalystSentryInstallGroups` - which is not ideal but works for now.

**Comment by rydurham** [comment]
In this scenario that may be the only option. Once you have published the migrations you should be able to edit them as you see fit.  

I am not familiar enough with ```utfmb4``` to know what else to do.

**Comment by lostfocus** [comment]
When WordPress is using `utf8mb4` tables, they seem to change the length of the index: [line 1679 in this file](https://github.com/WordPress/WordPress/blob/36de491d686473038714cc21646b7ff999652c27/wp-admin/includes/upgrade.php#L1679)

I don't think this is somewhere in Laravel and seems a bit excessive, just to make sure people get to put emoji in their usernames.

**Comment by rydurham** [comment]
I am going to close this for now.

**Comment by xXZang3tsuXx** [comment]
Change the AppServiceProvider.php as follows

<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Facades\Schema;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        Schema::defaultStringLength(191);
    }

    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }
}

**Comment by sible27** [comment]
@xXZang3tsuXx Gracias por el aporte me funciono, I want to know why the error is generated, if nothing has changed.

**Comment by lohiloki** [comment]
Any solution, still having the same issue

 Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `users` add unique `users_email_unique`(`email`))

after trying out above solution

**Comment by rydurham** [comment]
Which database driver are you using?

**Comment by lohiloki** [comment]
Hi rydurham, thanks for the reply, It's mysql and I found two solutions today, 
1. adding specific code to the file app/Providers/AppServiceProviders.php

```
use Illuminate\Support\Facades\Schema;
public function boot()
{
    Schema::defaultStringLength(191);
}
```
2. and id database.php which is in config folder where it says 
```
'charset' => 'utf8mb4',
'collation' => 'utf8mb4_unicode_ci',
```
I changed these to
```
'charset' => 'utf8',
'collation' => 'utf8_unicode_ci',
```

It worked fine. And for my new installation only 1st solution is the best one.

**Comment by rydurham** [comment]
That is excellent news!
