### ISSUE TITLE
Getting Ambiguous class resolution, "MigrationCartalystSentryInstallUsers"  in Composer version 1.0-dev

### ISSUE THREAD

**Issue by ideadx** [rydurham/Sentinel#161]

**Comment by rydurham** [comment]
What is the context in which this is coming up?

**Comment by ideadx** [comment]
@rydurham When running: 'composer update' or 'composer install' command 
http://imgur.com/kez1Kta
Thx.

**Comment by rydurham** [comment]
Interesting.  I am not able to reproduce this on Laravel 5.  Would you send me a stack trace?

**Comment by ideadx** [comment]
I have standard install of Mamp Pro on iMac. I think it has to do with psr-0 loader classmap entries.

**Comment by rydurham** [comment]
I have a plan for fixing this, but I am not sure when I will be able to implement it.

**Comment by ideadx** [comment]
@rydurham Thanks :+1:

**Comment by rydurham** [comment]
This should now be fixed in v2.2.3.

**Comment by ideadx** [comment]
Sorry mate but I just pulled in 2.2.3 and that Warning is still there.

**Comment by rydurham** [comment]
Try replacing your current sentry migrations with the new ones in 2.2.3 - does that fix the problem?

**Comment by rydurham** [comment]
Did that work for you?

**Comment by ideadx** [comment]
Its all good now, sorry for responding late. Thanks. :+1:
