### ISSUE TITLE
Custom routing logout URL generation error

### ISSUE THREAD

**Issue by james2doyle** [rydurham/Sentinel#162]
I was getting a failed URL generation error when using a custom route to logout.

I changed line [89 in the SessionController](https://github.com/rydurham/Sentinel/blob/master/src/controllers/SessionController.php#L89) to redirect back to login after destroying the session.

```php
return Redirect::route('sentinel.login');
```

This seems to work for me. Not sure if this was a problem for anyone else.

**Comment by rydurham** [comment]
What value did you have in the config for ```['routing']['session_destroy'```] before making that change?

**Comment by james2doyle** [comment]
I never overwrote the `['routing']['session_destroy']` method. Here is a snippet from the routes file:

```php
Route::group(['prefix' => 'admin'], function () {
  // Sentinel Session Routes
  Route::get('login', ['as' => 'sentinel.login', 'uses' => 'SessionController@create']);
  Route::get('logout', ['as' => 'sentinel.logout', 'uses' => 'SessionController@destroy']);
  Route::get('sessions/create', ['as' => 'sentinel.session.create', 'uses' => 'SessionController@create']);
  Route::post('sessions/store', ['as' => 'sentinel.session.store', 'uses' => 'SessionController@store']);
  Route::delete('sessions/destroy', ['as' => 'sentinel.session.destroy', 'uses' => 'SessionController@destroy']);
});
```

**Comment by rydurham** [comment]
Try changing [this line](https://github.com/rydurham/Sentinel/blob/master/src/config/sentinel.php#L123) in your published config file to 

```php
'session_destroy'  => ['route' => 'sentinel.login'],
```

and see if that helps address the issue.

**Comment by james2doyle** [comment]
Ok that did work. Thanks!
