### ISSUE TITLE
Getting the sentry user when using auth.basic

### ISSUE THREAD

**Issue by tzfrs** [rydurham/Sentinel#171]
Hello,

I have a route that uses `auth.basic` to log in users. After the user is logged in I want to access the user. I know, that I could do that via `Auth::getUser()` but I wanted to use `Sentry` at all points of my project where I'm using user management stuff.

How would I fix this? Is there a way through your library? Do I have to do a custom middlewareclass for `auth.basic` and save it myself like this

    $user = Auth::getUser();
    Sentry::login($user); 

?

**Comment by rydurham** [comment]
Hello!  I will see if I can help.   First, make sure this is the right package - are you using ```rydurham/sentinel``` or ```cartalyst/sentinel```?    

Assuming you are using ```rydurham/sentinel```, the easiest solution is to not use Laravel's default Auth code at all - everything you need is provided by the package.  Once you have completed the installation instructions you can use the ```sentry.auth``` middleware, and you can use ```Sentry::getUser()``` to retrieve the logged in user at (almost) and place within your application. 

Does that make sense?

**Comment by tzfrs** [comment]
Hi, yeah, I'm using `rydurham/sentinel`. However, when using sentry.auth, and the user is not allowed to access the page, the user gets redirected to the login page. I, however want a `auth.basic` that prompts like `.htaccess` and then saves that data to the `Sentry::getUser()` object. Would I need to write a custom Middleware for that?

**Comment by rydurham** [comment]
I am not sure I understand what you are trying to achieve.  You can change the  ```sentry.auth``` redirect location in the config files; is that what you are going for?

**Comment by tzfrs** [comment]
Ok, I'll try to be more clear. When using `auth.basic` I'm getting a .htaccess protection, right? However, when using `auth.basic` the user that has authenticated doesn't get saved into Sentry. So I can't access `Sentry::getUser()` after using `auth.basic`. However, I can't use `sentry.auth` since `sentry.auth` is not .htaccess, and I do need the login page in some cases, so I cannot overwrite it.

What I want to achieve is a .htaccess protected area where the logged in user will be available through the Sentry object. Something like this

`sentry.auth.basic`

Is this better to understand?

**Comment by rydurham** [comment]
I think I now understand what you are trying to achieve.   

Your best bet will probably be to write a custom middleware class that handles this for you.    The ```auth.basic``` middleware resolves the user credentials from the [Symfony\Components\HttpFoundation\Request](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/HttpFoundation/Request.php#L1036-L1044)  class.  You could write your middleware to grab those credentials and then run them through Sentry for authentication - that should solve your problem.
