### ISSUE TITLE
Missing error message if account is not activated on Materialize theme

### ISSUE THREAD

**Issue by tzfrs** [rydurham/Sentinel#173]
When using the materialize theme and trying to log in with a not activated account I'm not getting an error message. I looked into the source code and found this error

>Uncaught SyntaxError: missing ) after argument list

right here

    toast('You have not yet activated this account. <a href='http://vagrantipmanager.dev/reactivate' class='alert-link'>Resend Activation Email?</a>', 5000);

I guess the reason for this is because the toast is created with single quotes, however all the properties of the attributes are also done with single quotes. When using " instead of ' for the toast it works.

**Comment by rydurham** [comment]
Good catch! Care to submit a pull request?
