### ISSUE TITLE
Routes are listed but not working

### ISSUE THREAD

**Issue by ricardobarantini** [rydurham/Sentinel#174]
I finished the installation, when I give the command `php artisan route:list` all routes are listed but none are working.

Version:
"laravel/framework": "5.0.*"
"rydurham/sentinel": "~2"

Any thoughts?

**Comment by rydurham** [comment]
When you run ```php artisan list``` do you see the "sentinel:publish" command on the list?

**Comment by ricardobarantini** [comment]
Yes. I found the error. One of my route was missing an argument.
