### ISSUE TITLE
Soft Deleting 

### ISSUE THREAD

**Issue by adw-cr** [rydurham/Sentinel#182]
Hello, how i can trying implement Soft Delete in this package?

Laravel 5.1

Any suggestions?

**Comment by rydurham** [comment]
This should be doable.  Assuming you want to soft-delete your users (rather than your groups) try these steps: 

1.  Make sure your User model extends ```Sentinel\Models\User```
2. Add the ```Illuminate\Database\Eloquent\SoftDeletes``` trait to your user model
3. Create a migration that adds a nullable "deleted_at" timestamp column (```$table->softDeletes();```) to your users table. 

That should do it.  The Sentinel User Repository does not handle ```withTrashed()``` or ```onlyTrashed``` database queries, so you may need to extend the class and customize it to your needs.

**Comment by adw-cr** [comment]
I followed these steps, but I have not had results.

**Comment by rydurham** [comment]
Are you getting an error or are the models just being removed from the database completely?

**Comment by adw-cr** [comment]
My projetc no haves errors, but I cant not, make it work the soft deleted,

need add register model in config sentry file?

Thanks for your interest

**Comment by rydurham** [comment]
You shouldn't need to change the sentry config file.   Are you able to use
soft deletes for other models in your application?

**Comment by adw-cr** [comment]
Yes, i have other model whit soft deletes.

there a way to publish the package directly to my main folder app?

**Comment by rydurham** [comment]
Ah - I was wrong.  You should update the sentry config file so that it
knows the full namespace of your user class.

**Comment by adw-cr** [comment]
Oh my god, you are genius, my problem is resolved.

I have a question additional, this is strong, but for my is functional.
Is possible publish package Sentinel in my principal folder app, and not in my folder vendor, i want publish controller model routes, and other files.

is possible?

**Comment by rydurham** [comment]
Excellent news!  I am glad that worked out.

It is not reccomended that you publish the package in your main application
folder (for a variety of reasons.)  To get the package routes into your
main routes file you should just copy and paste manually.

**Comment by adw-cr** [comment]
i understand, but i will want create api rest, how i can that?

**Comment by adw-cr** [comment]
Again, i know that your time is gold, thanks for answers.

**Comment by rydurham** [comment]
You should be able to create a rest api without moving anything from the
package to the main application.   You can disable the html views for the
package by adjusting the "views_enabled" parameter in the sentinel config
file - that should help.

**Comment by adw-cr** [comment]
Perfect, this is other issue, thanks for your help.
