### ISSUE TITLE
Possible to authenticate without password?

### ISSUE THREAD

**Issue by asmafarhat2006** [rydurham/Sentinel#184]
Is it possible to authenticate with a user only by its id, for example?

Useful for debugging and/or live testing, as if we were someone else..similar to the impersonate feature. 

Hope I got the message through :)

**Comment by rydurham** [comment]
Yes, this is possible.  This package is a wrapper for the Cartalyst Sentry 2 authentication system.   Sentry has a ```login()``` method which does exactly what you need:  https://cartalyst.com/manual/sentry/2.1#sentry::login()
