### ISSUE TITLE
Token based Authentication with Sentinel

### ISSUE THREAD

**Issue by Moh-Mal** [rydurham/Sentinel#186]
Hi,
We're using Sentinle in our web app. Now, we need a token base authentication(like Oauth2) to handle our mobile app. Is there any solution to our requirement in Sentinel?
Thanks!

**Comment by rydurham** [comment]
Hello,

This package is a wrapper for the Cartalyst\Sentry 2 auth package.  It does not currently support token based authentication out of the box, but you may be able to find some resources discussing how to use Sentry with OAuth.
