### ISSUE TITLE
Reset blade template password bug and save error

### ISSUE THREAD

**Issue by mindtheroo** [rydurham/Sentinel#187]
It looks like the reset password page might be broken. I have a fresh install of Laravel and Sentinel with working email configuration. I can send and receive the password reset emails as expected. The email link takes me to the password rest page correctly. Without modifying the blade template, submitting the form just redirects back to the same reset form without any error messages.

The model found at Sentinel\FormRequests\ResetPasswordRequest expects just a single password with the name "password" while the form submits two fields named "newPassword" and "newPassword_confirmation." Updating the blade view to use field names "password" and "password_confirmation" does resolve the issue.

Laravel 5.1, PHP 5.5.12, Sentinel v2.2.4

**Comment by rydurham** [comment]
Which UI theme are you using?

**Comment by mindtheroo** [comment]
Should have included tht previously sorry about that: Materialize.
