### ISSUE TITLE
Pagination missing on users/index.blade.php and groups/index.blade.php

### ISSUE THREAD

**Issue by prestonreset** [rydurham/Sentinel#189]
Hi Ryan,

Thanks for fixing that reflash issue. I created a github acct. I really only use bitbucket.

The pagination exists in the user controller, but it doesn't have the code to display pagination. When the users table exceeds 15 in the standard template, that's all she wrote, so there is no way to edit users that are beyond 15.

**Comment by rydurham** [comment]
Which UI theme are you using?

**Comment by prestonreset** [comment]
It is the default bootstrap theme that is installed when you don't specifically select a theme.
https://github.com/rydurham/Sentinel/blob/master/src/views/bootstrap/users/index.blade.php

**Comment by prestonreset** [comment]
https://github.com/rydurham/Sentinel/blob/master/src/controllers/UserController.php

    /**
     * Display a paginated index of all current users, with throttle data
     *
     * @return View
     */
    public function index()
    {
        // Paginate the existing users
        $users       = $this->userRepository->all();
        $perPage     = 15;
        $currentPage = Input::get('page') - 1;
        $pagedData   = array_slice($users, $currentPage * $perPage, $perPage);
        $users       = new Paginator($pagedData, $perPage, $currentPage);
        return $this->viewFinder('Sentinel::users.index', ['users' => $users]);
    }
