### ISSUE TITLE
$this->be($user); in testing

### ISSUE THREAD

**Issue by kamaroly** [rydurham/Sentinel#191]
HI, 
Can anyone help me to use this package in laravel 5.1 testing same way I do $this->be($user) for laravel native authentication driver?
Thanks

**Comment by rydurham** [comment]
Hello! 

Unfortunately there is no good solution for this at the moment.   Eventually I hope to add some helper methods to the package that will make this easier.  

For the time being, you will probably want to write a trait that overwrites the $this->be() method in the Laravel TestCase class (which itself comes from the Laravel Testing Application Trait.) This is assuming that your tests extend the Laravel TestCase class, though. 

The trait should do something like the following, though I have not personally tested this yet: 

```php
$user = Sentry::findUserByLogin($email);
Sentry::login($user);
Event::fire('sentinel.user.login', ['user' => $user]);
```

The event is necessary for any tests that may rely on finding the user id or email in the Session store.   You could alternatively set those values manually if you don't want to deal with events firing.

**Comment by kamaroly** [comment]
Thank you. I will try this. It looks fine.
