### ISSUE TITLE
after installed I went to mydomin/login then got error

### ISSUE THREAD

**Issue by theatec900** [rydurham/Sentinel#195]
ErrorException in 7dd7e74765f2104aeb7d5f7bcaac514002163d02.php line 14:
Undefined variable: errors (View: /var/www/html/lab/laravel5/resources/views/sentinel/sessions/login.blade.php)

**Comment by theatec900** [comment]
my laravel version : 5.2
and rydurham/sentinel: 2.3

**Comment by theatec900** [comment]
hi,
I have solved that problem already. that problem was function Input::old is old.
but now, I have a new problem when i tried to mydomain/register 

I have found this error=>

BadMethodCallException in Controller.php line 103:
Method [beforeFilter] does not exist.

and i tried to change beforeFilter to middleware in "vendor/rydurham/sentinel/src/controllers/RegistrationController.php line 43"
then I found a new error is =>

ReflectionException in Container.php line 738:
Class Sentinel\csrf does not exist

and I dont know how to solve it.

**Comment by rydurham** [comment]
This has been fixed in v2.3.1.  Thanks for giving me the heads up!

**Comment by theatec900** [comment]
Hi,
when I tried to mydomain/register is still error like this below 

BadMethodCallException in Controller.php line 103:
Method [beforeFilter] does not exist.

**Comment by rydurham** [comment]
Sorry about that!  Should be fixed now in v2.3.2.
