### ISSUE TITLE
The "force" option does not exist.  

### ISSUE THREAD

**Issue by deafirefly** [rydurham/Sentinel#199]
php artisan  sentinel:publish

                                                                  
  [Symfony\Component\Console\Exception\InvalidArgumentException]  
  The "force" option does not exist.                              
                                                                  

Not sure if I did this right but see if you have seen this before.  

Rodney

**Comment by deafirefly** [comment]
I saw closed issue about this one and I checked env file to make sure this APP_ENV=local is there.  It is.   

Not sure what I miss.

**Comment by rydurham** [comment]
This has been fixed in v2.3.3.
