### ISSUE TITLE
render() not working on users.index and groups.index

### ISSUE THREAD

**Issue by Razorsheep** [rydurham/Sentinel#200]
When I try to render the paginator ( laravel 5.1 using branch 2.2 )

```php
{!! $groups->render() !!}
```
or 
```php
{!! $users->render() !!}
````

in the respective index views nothing is rendered. If I test the same using
```php
User::paginate(15);
```
in the Sentinel UsersController the paginator works fine in the index view.

**Comment by rydurham** [comment]
This has been fixed in v2.3.4.
