### ISSUE TITLE
how to disable throttling checking point ?

### ISSUE THREAD

**Issue by budisuryana** [rydurham/Sentinel#202]
i was disable on config/cartalyst.sentinel and comment in my script login authentication, but when login i get error "The Username or Password is incorrect."
![2](https://cloud.githubusercontent.com/assets/12753432/15103742/512bddc4-15d9-11e6-844d-1da8a1401a2f.png)
![3](https://cloud.githubusercontent.com/assets/12753432/15103744/55362546-15d9-11e6-806f-a7b7abf9a7e8.png)

**Comment by rydurham** [comment]
It looks like you are using Cartalyst\Sentinel and not rydurham\sentinel, is that the case?

**Comment by budisuryana** [comment]
whoops , yeah sorry
