### ISSUE TITLE
Laravel sentinel mail send no response

### ISSUE THREAD

**Issue by yokes-g-wiredelta** [rydurham/Sentinel#203]
i have installed latest laravel 5.2 version, and i have installed the Laravel Sentinel plugin from this git URL:https://github.com/rydurham/Sentinel and it seems all the functionalities seems working fine for example,

Create a new user 2)Create a new group
Edit and delete Group and it's User,
But i facing issues with sending the mail while creating a new user, all the templates regarding the mail is already there in the view's folder, but mail is not sending while create a new user, even i can't able to Override those functionalities, so any one have an idea to fix this issue?

**Comment by rydurham** [comment]
First make sure that your email settings are correct.  Are you able to send other mail via your application?

**Comment by Blackops404** [comment]
hi
how can i use queue when send email for registration , or reset active code?
i can't find where is function for send an email on this package

**Comment by rydurham** [comment]
Email delivery is triggered by events and messages are sent via a queue (if one is being used) by default.  
[https://github.com/rydurham/Sentinel/blob/master/src/Sentinel/Listeners/UserEventListener.php](
https://github.com/rydurham/Sentinel/blob/master/src/Sentinel/Listeners/UserEventListener.php)

**Comment by Blackops404** [comment]
@rydurham tnx man for fast answer
