### ISSUE TITLE
Adding recpatcha to the login/registration pages

### ISSUE THREAD

**Issue by overint** [rydurham/Sentinel#204]
Hi!
I'm not sure how to go about this the correct way. Would it be best to just create a fork and modify that, or is there any other way to integrate recaptcha?

**Comment by rydurham** [comment]
My advice would be to create your own login controller (start by making a copy of the Sentinel login controller) and then add your custom logic there.  You will need to disable the default Sentinel routes, create your own routes and then update your views to make use of those new routes.

**Comment by overint** [comment]
Thanks for the suggestion. My new controller works well.
