### ISSUE TITLE
resend activation email if user is already registered

### ISSUE THREAD

**Issue by tusharvikky** [rydurham/Sentinel#208]
Hello,

If the user is already registered and he hasn't activated the account. Can we just resend the activation mail again if he submits login or registration form?

**Comment by rydurham** [comment]
Currently a user will be prompted with the option to resend their activation email if they attempt to log in without having activated their account.   

https://github.com/rydurham/Sentinel/blob/master/src/Sentinel/Repositories/Session/SentrySessionRepository.php#L98

**Comment by tusharvikky** [comment]
Yes. True. Re-sending account activation email would be a good idea if the user hasn't yet activated. When he or she tries to register/login again with inactive account email. 

Also, while account activation email is sent via /reactivate, if the user enters invalid email id we should return with Account not found instead of success (check email) message. 

https://github.com/rydurham/Sentinel/blob/master/src/Sentinel/Repositories/User/SentryUserRepository.php#L258

**Comment by rydurham** [comment]
I am open to a pull request if you are interested.

**Comment by tusharvikky** [comment]
I'm on ~v2.2. No update yet. :(

**Comment by rydurham** [comment]
I haven't tagged a new version
yet.![](https://link.nylas.com/open/6xdlcp00tmqroo6b9v5xsbx1u/local-49a5bf5b-
555b?r=cmVwbHkrMDAwYTRhMmJkYmJhZDcxMTAyN2IxMTc2YTRmMzU0ZmY2NjY5NDhlNGMzMTY3NjhlOTJjZjAwMDAwMDAxMTM4ZDQxYzg5MmExNjljZTA5YWNlN2FhQHJlcGx5LmdpdGh1Yi5jb20=)

On Jun 30 2016, at 1:23 pm, Tushar Deo &lt;notifications@github.com&gt; wrote:  

> I'm on ~v2.2. No update yet. :(

>

> —  
> You are receiving this because you modified the open/close state.  
> Reply to this email directly, [view it on
GitHub](https://github.com/rydurham/Sentinel/issues/208#issuecomment-229777904&r=cmVwbHkrMDAwYTRhMmJkYmJhZDcxMTAyN2IxMTc2YTRmMzU0ZmY2NjY5NDhlNGMzMTY3NjhlOTJjZjAwMDAwMDAxMTM4ZDQxYzg5MmExNjljZTA5YWNlN2FhQHJlcGx5LmdpdGh1Yi5jb20=),
or [mute the thread](https://github.com/notifications/unsubscribe
/AApKKxa_PtcLW0X_HnwAww-_67hTNW5vks5qRCXIgaJpZM4I-
jGK&r=cmVwbHkrMDAwYTRhMmJkYmJhZDcxMTAyN2IxMTc2YTRmMzU0ZmY2NjY5NDhlNGMzMTY3NjhlOTJjZjAwMDAwMDAxMTM4ZDQxYzg5MmExNjljZTA5YWNlN2FhQHJlcGx5LmdpdGh1Yi5jb20=).![](https://github.com/notifications/beacon
/AApKK5aAQYq-4g_CDMNl9oZKegEayhuAks5qRCXIgaJpZM4I-jGK.gif)

**Comment by tusharvikky** [comment]
Could you please tag a v2.2.6 with this commit?

**Comment by rydurham** [comment]
I just tagged v2.2.6 - sorry that took so long.   You may want to double check that everything is working as intended.

**Comment by tusharvikky** [comment]
Seems to have an issue with line https://github.com/rydurham/Sentinel/blob/ef862ede26d510fc4181d6583c707ec38ff09222/src/Sentinel/Repositories/User/SentryUserRepository.php#L275 and L303 being interchanged.

**Comment by rydurham** [comment]
Good catch!  That is now fixed in v2.2.7.
