### ISSUE TITLE
Sentinel for laravel 5.3

### ISSUE THREAD

**Issue by Harrrrry** [rydurham/Sentinel#212]
Sentinel package is compatible with 5.3 laravel version ??

**Comment by overint** [comment]
+1

**Comment by rydurham** [comment]
I have just tagged v2.5.0 which should now be Laravel 5.3 compatible.    It could do with some more testing - let me know if you run into any issues.

**Comment by kamaroly** [comment]
I just installed 2.5 on laravel 5.3 but I am getting below error, I have done migration and seeding. Why doesn't it detect Id of the users table?
```php
QueryException in Connection.php line 769:
SQLSTATE[42S22]: Column not found: 1054 Unknown column '' in 'where clause' (SQL: select * from `users` where `` = 2 and `persist_code` = IhYedJhrBNhu7FK1jfzR85jSR0WYMrMzjyPorpi3gWNBPVbC5KJugQ7gqguw limit 1)
```

What could be the issue ?

**Comment by kamaroly** [comment]
I solved it, I had to clear the cookies of my browser.

![image](https://cloud.githubusercontent.com/assets/3633772/20648352/16a6ec8e-b4ad-11e6-8042-8869b3d812d8.png)
