### ISSUE TITLE
Add the "permission" keyword to the short description of the repository

### ISSUE THREAD

**Issue by Noir-** [rydurham/Sentinel#213]
I was searching a long time for a RBAC/ACL library which is suitable for my Laravel project. This library is exactly what I need and I'm baffled how active this project is and that I found this library pretty late.

The main reason for this is that I searched for terms like "laravel permission", "laravel acl" and "laravel rbac" on Google and GitHub. On GitHub this package is NOT shown and only on page 4 at least for "my version" of Google using my keywords. (Google ranking is hardly reproducible).

So I suggest to add at least the "permission" keyword to the short description of this repository to make it more visible. Maybe like this:

> A package to add advanced permission functionality to Laravel based on Sentry http://www.ryandurham.com/projects/sentinel/

**Comment by rydurham** [comment]
Hello Noir,

This is a good idea, and I may take you up on it.  However, this package is really just a bridge - it provides a laravel integration for Cartalyst\Sentry, which is the package that really does the heavy lifting as far as ACL is concerned.    As it happens, Cartalyst\Sentry has been deprecated in favor of Cartalyst\Sentinel, which is essentially Sentry V3.   I have a laravel wrapper package for that ACL system as well, which can be found here: https://github.com/srlabs/centaur

**Comment by Noir-** [comment]
Oh I over read the deprecation notice, thanks for the advice!
However it seems that the other wrapper package needs a permission related keyword too. :smile:
