### ISSUE TITLE
Compatibility for Laravel 5.4

### ISSUE THREAD

**Issue by peterjaap** [rydurham/Sentinel#222]
I'm now getting;

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - rydurham/sentinel v2.5.0 requires illuminate/support 5.3.* -> satisfiable by laravel/framework[v5.3.28], illuminate/support[v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - rydurham/sentinel v2.5.0 requires illuminate/contracts 5.3.* -> satisfiable by laravel/framework[v5.3.28], illuminate/contracts[v5.3.0, v5.3.16, v5.3.23, v5.3.4].
```

**Comment by rydurham** [comment]
This won't be possible until the dependencies used by this package themselves release 5.4 compatible versions.

**Comment by rydurham** [comment]
I have now pushed v2.6 with support for Laravel 5.4.     The big change is a switch from the old mail system to the use of Mailables.   The package tests are passing, but I strongly recommend you run your own tests as part of your upgrade.   Any help you can offer with testing would be greatly appreciated. 

The other minor change was updating the way that the Sentry singletons are being registered in the SentryServiceProvider - that should have an impact on anything else.

Heads up:  given that Sentry has been deprecated for a while now, I will probably eventually be deprecating this package as well.

**Comment by rydurham** [comment]
It looks like there is a compatibility problem with php 5.6.    I am going to bump up the minimum required version to 7 for this release.   If there is desire for a 5.6 compatible version that can be discussed in a different issue.

**Comment by sharifghaderi** [comment]
Hi,
I just want to know if the current Sentinel package is compatible with laravel 5.4 or not. 
I'm using php 7 with laravel 5.4.
Can you please tell me if it works or not before I install it and then have to go through the headache of removing it. 
Thanks

**Comment by rydurham** [comment]
Yes.  There is a 5.4 compatible version of this package, as is stated in the readme.
