### ISSUE TITLE
View [home] not found.

### ISSUE THREAD

**Issue by nardnahcayaj** [rydurham/Sentinel#228]
When home url is added , we are facing this error. The home template is not available, but the package is depends on that.

**Comment by rydurham** [comment]
What does your home route look like?   Do you have a stack trace?

**Comment by Rahulsharma0810** [comment]
Just Duplicate welcome.blade.php with home.blade.php 
or you can add this landing.

`<!doctype html>
<html lang="{{ config('app.locale') }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>

        
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">

        
        <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Raleway', sans-serif;
                font-weight: 100;
                height: 100vh;
                margin: 0;
            }
            .full-height {
                height: 100vh;
            }
            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }
            .position-ref {
                position: relative;
            }
            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }
            .content {
                text-align: center;
            }
            .title {
                font-size: 84px;
            }
            .links > a {
                color: #636b6f;
                padding: 0 25px;
                font-size: 12px;
                font-weight: 600;
                letter-spacing: .1rem;
                text-decoration: none;
                text-transform: uppercase;
            }
            .m-b-md {
                margin-bottom: 30px;
            }
        </style>
    </head>
    <body>
        <div class="flex-center position-ref full-height">
            
                <div class="top-right links">
                
                        <a href="{{ url('/profile') }}">Profile</a>
                        <a href="{{ url('/profile/edit') }}">Profile Edit</a>
                        <a href="{{ url('/users') }}">Users</a>
                        <a href="{{ url('/users/create') }}">Users Create </a>
                        <a href="{{ url('/groups') }}">Groups  </a>
                        <a href="{{ url('/groups/create') }}">Groups Create </a>
                    
                </div>
            

            <div class="content">
                <div class="title m-b-md">
                    Dashboard
                </div>
            </div>
        </div>
    </body>
</html>`

**Comment by rydurham** [comment]
I am sorry I missed this - were you able to solve your problem?

**Comment by rydurham** [comment]
I am going to close this for now - we can reopen it if this is still a problem.
