### ISSUE TITLE
See the password in a View

### ISSUE THREAD

**Issue by luarcito** [rydurham/Sentinel#230]
Hi,
Sorry for my English.
I would like to know if I can make the password for an account show in a view. I do not know how to decode it.
Thanks in advance.

**Comment by rydurham** [comment]
Hello @luarcito, 

Displaying a password in plain text is not a recommended security practice.  It is not possible to decode the hashed password values, so the only way to accomplish this would be to store the password in plaintext in the database, which is a major security concern. 

~Ryan

**Comment by rydurham** [comment]
I am going to close this for now, but we can re-open it if you would like to discuss this further.
