### ISSUE TITLE
Class cache does not exist 

### ISSUE THREAD

**Issue by fridzema** [rydurham/Sentinel#232]
Hello,

I have the same problem as mentioned in #231 but i have this error after package install (at the vender publish), even before i can test it out.

Piece of my configuration:
CACHE_DRIVER=redis
SESSION_DRIVER=redis
QUEUE_DRIVER=sync

My application is full of things that use caching, so caching should not be the problem.

Hope you can help me out with this?

**Comment by rydurham** [comment]
Hello!   I am sorry I missed this - were you able to sort it out?   Do you have a stack trace?

**Comment by fridzema** [comment]
Hello, 
No problem! 
It was a time ago so i don't know exactly what i have did to fix it unfortunately. 
Thanks for your response ;)
