### ISSUE TITLE
rydurham/Sentinel + RBAC

### ISSUE THREAD

**Issue by AlexMcowkin** [rydurham/Sentinel#235]
Hello.
I neeed use RBAC.
what is the best package that will work with your package?

**Comment by rydurham** [comment]
What does RBAC stand for?

**Comment by AlexMcowkin** [comment]
Hi
RoleBaseAccessControll. this abbreviation is from yii

in laravel we have ACL

**Comment by rydurham** [comment]
Good news:   As I mentioned in my other message, this package is a wrapper for the Cartalyst/Sentry package, which offers tools for role based access control.  If you read through the documentation link I sent you, you should find everything you need.

**Comment by AlexMcowkin** [comment]
Hi
can you give me link?
cause https://github.com/cartalyst/sentry is deprecated
